name: recsys-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - alembic=1.18.4=pyhcf101f3_0
  - anyio=4.12.1=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311hf197a57_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.2.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.18.0=pyhcf101f3_0
  - bcrypt=5.0.0=py311hd2a4513_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py311h7e844b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py311h137bacd_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - comm=0.2.3=pyhe01879c_0
  - configparser=7.2.0=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h9d13916_4
  - cryptography=46.0.5=py311h7b58bf4_0
  - cycler=0.12.1=pyhcf101f3_2
  - databricks-cli=0.17.3=pyhd8ed1ab_0
  - debugpy=1.8.20=py311hc63dfec_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-py=7.1.0=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - faiss=1.9.0=py311h6c24f5f_0_cpu
  - faiss-cpu=1.9.0=he781eb1_0
  - filelock=3.24.3=pyhd8ed1ab_0
  - flask=3.1.3=pyhcf101f3_1
  - fonttools=4.61.1=py311he13f9b5_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.10.4=h4cff582_1
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - gorilla=0.4.0=pyhd8ed1ab_1
  - greenlet=3.1.1=py311h6d0c2b6_0
  - gunicorn=25.1.0=py311h6eed73b_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hf5e326d_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - invoke=2.2.1=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyhe01879c_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - khronos-opencl-icd-loader=2024.10.24=h6e16a3a_1
  - kiwisolver=1.4.9=py311h591569d_2
  - krb5=1.21.3=h37d8d59_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20240116.2=cxx17_hf036a51_1
  - libblas=3.11.0=5_he492b99_openblas
  - libboost=1.88.0=h0078366_0
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libfaiss=1.9.0=h0cb9d5e_0_cpu
  - libffi=3.4.4=hecd8cb5_1
  - libgcc=15.2.0=h08519bb_18
  - libgfortran=15.2.0=h7e5c614_18
  - libgfortran5=15.2.0=hd16e46c_18
  - liblapack=3.11.0=5_h859234e_openblas
  - liblightgbm=4.6.0=cpu_hca925f8_7
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=4.25.3=h34eed0b_0
  - libsodium=1.0.20=hfdf4475_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libtorch=2.4.1=cpu_mkl_h28efb88_100
  - libuv=1.51.0=h58003a5_1
  - libwebp-base=1.6.0=hb807250_0
  - lightgbm=4.6.0=cpu_py_ha6cb263_7
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hf0c8a7f_0
  - mako=1.3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py311he13f9b5_0
  - matplotlib-base=3.10.0=py311h919b35b_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2023.2.0=h694c41f_50502
  - mlflow=1.2.0=py_1
  - mpmath=1.4.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - notebook=7.5.4=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py311hc43a94b_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=h240833e_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.6.1=hb6871ef_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py311hca9a5ca_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.6=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=11.1.0=py311h935ef2f_1
  - pip=26.0.1=pyhc872135_0
  - platformdirs=4.9.2=pyhcf101f3_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - protobuf=4.25.3=py311h6b31176_1
  - psutil=7.2.2=py311ha332486_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.11.0=pyhd8ed1ab_0
  - pynacl=1.6.2=py311hc71d4c3_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.4.1=cpu_mkl_py311h96a8c7d_100
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.3=py311h53ebfaf_1
  - pyzmq=27.1.0=py311h0ab6910_0
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - readline=8.3=h49f2429_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py311hd2a4513_0
  - scikit-learn=1.8.0=np2py311heeb2b4f_1
  - scipy=1.16.3=py311hd77d3c2_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.2=py311hecd8cb5_1
  - setuptools=78.1.1=py311hecd8cb5_0
  - simplejson=3.20.2=py311hf197a57_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h289094c_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sqlalchemy=2.0.41=py311hd53568b_0
  - sqlite=3.50.2=hc8b0dd6_1
  - sqlparse=0.5.5=pyhcf101f3_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py311ha837bc1_0
  - sympy=1.14.0=pyh04b8f61_6
  - tabulate=0.9.0=pyhcf101f3_3
  - tbb=2021.8.0=ha357a0b_0
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=h3a5a201_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.2=py311h5547dcb_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=he532380_0
  - unicodedata2=17.0.1=py311hc71d4c3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - werkzeug=3.1.6=pyhcf101f3_0
  - wheel=0.45.1=py311hecd8cb5_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
prefix: /opt/anaconda3/envs/recsys-env
